### ISSUE TITLE
Swipe to return Previous page

### ISSUE THREAD

**Issue by Alfaizkhan** [JonasWanke/swipeable_page_route#11]
Hey Jonas,
First of all Thank you for this cool plugin.
I want you add the swipe right to return previous page that we will pop from as my client wants.

Can you please reply ASAP, if it is possible of not.

Thank you.

**Comment by JonasWanke** [comment]
I'm not quite sure what exactly this issue is about, as swiping to return to the previous page is the core of this package. Do you want to pop multiple pages at once when swiping?

**Comment by Alfaizkhan** [comment]
No,
You got me wrong,
I want it like a **PageView**.
Currently, i can swipe only LTR, not RTL.
note: in your example, for RTL, you used button to navigate.

**Comment by JonasWanke** [comment]
In that case, using a `PageView` with a [custom transition](https://medium.com/flutter-community/a-deep-dive-into-pageview-in-flutter-with-custom-transitions-581d9ea6dded) sounds like the way to go. There are also packages available to simplify this, e.g., [<kbd>transformer_page_view</kbd>](https://github.com/best-flutter/transformer_page_view).
