### ISSUE TITLE
Issue with back button gesture on Nokia (maybe bug maybe feature)

### ISSUE THREAD

**Issue by zim32** [JonasWanke/swipeable_page_route#13]
Hi. First of all thanks to your work. Plugin is awesome.
But I noticed some issue which leads to poor user experience. 

I have Android Nokia phone, which does not have back button, instead it uses swipes from the edge of screen to navigate back.
So when I want for example to go back and try to swipe from left to right and start swiping close to the left screen edge, builtin Nokia swipe detection activates and this plugin also begin to swipe. 

And this leads to double back and application closes. I think the solution here is will be to specify how far from edge the swipe must begin to activate navigation. 

**Porosal**

Something like that can help

```
return SwipeablePageRoute(
    builder: (context) => SomePageWIdget(),
    canOnlySwipeFromEdge: true,
    backGestureDetectionWidth: 150,
    minEdgeOffset: 50 // imaginary param
);
```

This gives some imaginary vertical line which starts at 50 from left, have width of  100 and ends at 150 from left.
And this will prevent simultaneous activation of builtin back button and this plugin.

**Comment by zim32** [comment]
See this link for description
https://developer.android.com/training/gestures/gesturenav

**Comment by JonasWanke** [comment]
Thanks for filing this issue (and creating the PRs!) and sorry for the delayed response.

I tried to reproduce this issue on my OnePlus phone where I also swipe from the edge to go back in every app but wasn't able to reproduce this problem. When swiping from the edge, the OS detects this gesture directly and Flutter doesn't receive pointer events at all, hence only one back navigation is performed.

I can still include the suggested `minEdgeOffset` parameter, but it should be used with care: Its value has to precisely match the OS configuration to avoid the problem you mentioned while not creating a gap between the OS's and app's gesture detection areas. Also, the behavior apparently differs between devices…

**Comment by zim32** [comment]
This is really strange. I my nokia I have stock android. Maybe your phone have another implementation of this feature... I will try to make a video of this issue
