### ISSUE TITLE
Animated title does not use styles or color from appbar

### ISSUE THREAD

**Issue by Tomas-TravelUnion** [JonasWanke/swipeable_page_route#21]
**Describe the bug**

When animating transition, inside of animation builder there is AnimatedTitle class that does not take style from app bard configuration, and it uses textStyle heading 6 color during transition. Making title to appear with wrong style and color during transition.

To reproduce just set in AppBarTheme or on MorphingAppBar foreground color to anything but default.

**Environment:**

* OS version:  
* Flutter version:  
* Package version:

**Comment by JonasWanke** [comment]
This is fixed in [v0.3.0](https://pub.dev/packages/swipeable_page_route/changelog#030--2023-01-24)
