### ISSUE TITLE
Hello, please update dependencies for flutter 3.10

### ISSUE THREAD

**Issue by Anykeykin** [JonasWanke/swipeable_page_route#26]
Hello, please update dependencies, required black_hole_flutter for flutter 3.10

**Comment by JonasWanke** [comment]
I released [<kbd>black_hole_flutter</kbd>](https://pub.dev/packages/black_hole_flutter) [v1.0.2](https://pub.dev/packages/black_hole_flutter/changelog#102--2023-05-11) a few hours ago, which contains the fix for Flutter 3.10.0
