### ISSUE TITLE
I am getting error on 'flutter pub get'

### ISSUE THREAD

**Issue by badaween-ahmed** [JonasWanke/swipeable_page_route#3]
Running "flutter pub get" in counter_app...                      
Because every version of flutter_test from sdk depends on test_api 0.2.19-nullsafety.2 which depends on async >=2.5.0-nullsafety <2.5.0, every version of flutter_test from sdk requires async >=2.5.0-nullsafety <2.5.0.

And because every version of swipeable_page_route depends on list_diff ^1.3.0 which depends on async >=2.2.0 <2.5.0, flutter_test from sdk is incompatible with swipeable_page_route.

So, because counter_app depends on both swipeable_page_route ^0.1.4 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because counter_app depends on both swipeable_page_route ^0.1.4 and flutter_test any from sdk, version solving failed.)
exit code 1

**Comment by JonasWanke** [comment]
As the error message describes, the `list_diff` dependency restricts compatible versions of `async` to `>=2.2.0 <2.5.0`. There's already an issue (including a workaround) for that: marcelgarus/list_diff#4

**Comment by marcelgarus** [comment]
Fixed this with version 1.3.2 of `list_diff`.

**Comment by marcelgarus** [comment]
Fixed this with version 1.3.2 of `list_diff`.
