### ISSUE TITLE
Is there a callback like `WillPop` that detects and allows swipeback?

### ISSUE THREAD

**Issue by son** [JonasWanke/swipeable_page_route#56]
Thank you for great package.

Is there a callback like `WillPop` that detects and allows swipeback?

If not, I would like to receive any information that would be helpful for forking.

**Comment by JonasWanke** [comment]
No, there isn't a callback for that. You can, however, update `context.getSwipeablePageRoute().canSwipe` dynamically to enable/disable swiping.

If you want to add a callback, the gesture handler code lives here:

https://github.com/JonasWanke/swipeable_page_route/blob/318182ec4ad6284e13fb02497fd52fe10cd9be3e/lib/src/page_route.dart#L625-L629

Notably, `enabledCallback()` includes the check whether `canSwipe` is `true`.

**Comment by son** [comment]
Awesome! thank you!
