### ISSUE TITLE
It is conflict with TabBar&TabBarView

### ISSUE THREAD

**Issue by houleixx** [JonasWanke/swipeable_page_route#6]
It is conflict with TabBar&TabBarView。
It is conflict with  ListView( scrollDirection : Axis.horizontal)。

**Comment by JonasWanke** [comment]
Could you please share a few more details on what the problem is, preferably including the source code and error logs? The example shows this package working with a `TabBar`:
https://github.com/JonasWanke/swipeable_page_route/blob/eac6942d0b6056accfaeb2ddedfd75a0f0b25c17/example/lib/main.dart#L116-L125
(which works both with `isScrollable = false` and `isScrollable = true`).

**Comment by houleixx** [comment]
Can not scroll if ListView (scrollDirection: Axis.horizontal)，default is page back.

--------------------------------------------------------------
`import 'package:flutter/material.dart';

import 'package:swipeable_page_route/swipeable_page_route.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      // debugShowMaterialGrid: true,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('主页'),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.of(context).push(SwipeablePageRoute(
              builder: (BuildContext context) => SecondPage(),
            ));
          },
          child: Text('go'),
        ),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        children: [
          Container(height: 100),
          Container(
            height: 200,
            child: ListView.builder(
              shrinkWrap: true,
              scrollDirection: Axis.horizontal,
              itemBuilder: (context, index) {
                return Container(
                  margin: EdgeInsets.only(right: 20),
                  color: Colors.blue,
                  height: 200,
                  width: 100,
                  child: Center(child: Text(index.toString())),
                );
              },
              itemCount: 20,
            ),
          ),
          Container(height: 100),
        ],
      ),
    );
  }
}
`

**Comment by houleixx** [comment]
TabBarView can not change

**Comment by JonasWanke** [comment]
Unfortunately, I haven't found a way to allow horizontal scrolls between tabs in the content area, but to swipe back when the user is on the left-most tab. Hence, there's an extra parameter in the `SwipeablePageRoute` constructor: setting `onlySwipeFromEdge` to `true` allows the user to swipe back (if they start the swipe near the left edge of the screen) or swipe between tabs (by starting their swipes further to the right). I'll update the example to also showcase this feature.
