### ISSUE TITLE
flexibleSpace not supported

### ISSUE THREAD

**Issue by proformance** [JonasWanke/swipeable_page_route#63]
When using the current latest version v0.4.3 it flickers when trying to use flexibleSpace in either of MorphingAppBar or MorphingSliverAppBar.

https://github.com/user-attachments/assets/05f11664-3f1c-4d59-ad0a-affcaa47c101

**Comment by JonasWanke** [comment]
Released as [v0.4.4](https://pub.dev/packages/swipeable_page_route/changelog#044--2024-08-13)
