### ISSUE TITLE
question: Is this trying to imitate how ios works ?

### ISSUE THREAD

**Issue by gedw99** [JonasWanke/swipeable_page_route#7]
If it is does Flutter core have this anyway ?

https://github.com/flutter/flutter/issues/57202

https://pub.dev/packages/cupertino_will_pop_scope

**Comment by JonasWanke** [comment]
The `SwipeablePageRoute` class is, in fact, a modified version of `CupertinoPageRoute` that allows for swiping back anywhere on the page unless `onlySwipeFromEdge` is `true`. I'll improve the README to better point this out.

This package, however, also provides the [`MorphingAppBar`](https://pub.dev/documentation/swipeable_page_route/latest/swipeable_page_route/MorphingAppBar-class.html) and `MorphingSliverAppBar` classes.

**Comment by JonasWanke** [comment]
This should be clearer in the new README of [v0.2.0](https://github.com/JonasWanke/swipeable_page_route/releases/tag/v0.2.0), and `SwipeablePageRoute` now directly inherits from `CupertinoPageRoute`.
