### ISSUE TITLE
Readme on Pub Dev has a mistake

### ISSUE THREAD

**Issue by ArbestNew** [JonasWanke/swipeable_page_route#76]
**Describe the bug**

In 2nd code block of first section https://pub.dev/packages/swipeable_page_route#swipeablepageroute

```
Navigator.of(context).push(SwipeablePageRoute(
  onlySwipeFromEdge: true,
  builder: (BuildContext context) => MyHorizontallyScrollablePageContent(),
));
```
`onlySwipeFromEdge ` in 2nd line is not a property of SwipeablePageRoute class

should be `canOnlySwipeFromEdge`.

Please verify this as developer of this project and update doc if needed.

Thank you for your works in advnace! 😁

**Environment:**

- OS version:  
- Flutter version:  
- Package version:

**Comment by JonasWanke** [comment]
Thanks for reporting this! It's fixed in [v0.4.6](https://pub.dev/packages/swipeable_page_route/changelog#046--2024-12-18)
