### ISSUE TITLE
Option to disable swiping

### ISSUE THREAD

**Issue by GrbavaCigla** [JonasWanke/swipeable_page_route#8]
Page I made uses `SlidingUpPanel` and `SwipeablePageRoute`, but I don't want to be able to swipe both panel and page route. Is there a way to disable page swiping? I forked the repository and I will try to implement it, but I am not that good with flutter.

**Comment by JonasWanke** [comment]
I'm not sure if I understand your request, as being swipeable is the whole point of the `SwipeablePageRoute` class. Do you want to dynamically turn off that behavior via, e.g., a parameter?

**Comment by GrbavaCigla** [comment]
Yes

**Comment by GrbavaCigla** [comment]
Wait, why is `canSwipe` final? I thought of changeable `canSwipe`. `SlidingUpPanel` is on the swipeable page, and I want to set `canSwipe` off each time `SlidingUpPanel` is pulled up (and on when it is pulled down).

**Comment by GrbavaCigla** [comment]
Thank you for your efforts :)

**Comment by simplenotezy** [comment]
@JonasWanke can you also ensure that canOnlySwipeFromEdge is not final? So that it can be changed dynamically aswell?

It would create a better UX when using in combination with TabBarView, so that when you swipe from edge, it goes back, otherwise it swipes inside the TabBarView
